-- Kala Nidhi artisan studio. Run the whole file in Supabase > SQL Editor.
-- It also adds the two new product columns to the original Kala Nidhi schema.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'artisan' check (role in ('artisan', 'buyer')),
  craft_specialty text,
  location text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  artisan_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  category text not null,
  price numeric not null check (price >= 0),
  image_url text,
  description text,
  hindi_description text not null default '',
  image_path text not null default '',
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists hindi_description text not null default '';
alter table public.products add column if not exists image_path text not null default '';
alter table public.profiles enable row level security;
alter table public.products enable row level security;

-- Each artisan can read and manage their own profile and listings.
-- These replace the original demo's public-read policies.
drop policy if exists "Public can view profiles" on public.profiles;
drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select to authenticated
using (auth.uid() = id);
drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert to authenticated
with check (auth.uid() = id and role = 'artisan');
drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update to authenticated
using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Public can view products" on public.products;
drop policy if exists "Artisans can view their products" on public.products;
create policy "Artisans can view their products" on public.products for select to authenticated
using (auth.uid() = artisan_id);
drop policy if exists "Artisans can publish products" on public.products;
create policy "Artisans can publish products" on public.products for insert to authenticated
with check (
  auth.uid() = artisan_id and exists (
    select 1 from public.profiles where id = auth.uid() and role = 'artisan'
  )
);
drop policy if exists "Artisans can delete their products" on public.products;
create policy "Artisans can delete their products" on public.products for delete to authenticated
using (auth.uid() = artisan_id);

-- Create the artisan profile from sign-up form metadata.
create or replace function public.handle_new_artisan()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role, craft_specialty, location)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''),
    case when new.raw_user_meta_data->>'role' = 'buyer' then 'buyer' else 'artisan' end,
    new.raw_user_meta_data->>'specialty', new.raw_user_meta_data->>'location')
  on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_artisan();

-- Fill missing profiles for existing auth users. Existing profiles stay intact.
insert into public.profiles (id, full_name, role, craft_specialty, location)
select id, coalesce(raw_user_meta_data->>'full_name', ''),
  case when raw_user_meta_data->>'role' = 'buyer' then 'buyer' else 'artisan' end,
  raw_user_meta_data->>'specialty', raw_user_meta_data->>'location'
from auth.users on conflict (id) do nothing;

-- Public bucket: product photos are accessible to anyone with their image URL.
-- Existing bucket settings are preserved. Set product-images to PUBLIC in Storage
-- if you already created it as a private bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 8388608, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

drop policy if exists "Artisans upload own product images" on storage.objects;
create policy "Artisans upload own product images" on storage.objects for insert to authenticated
with check (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Public view product images" on storage.objects;
create policy "Public view product images" on storage.objects for select
using (bucket_id = 'product-images');
drop policy if exists "Artisans remove own product images" on storage.objects;
create policy "Artisans remove own product images" on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text);
